export const ActionType = {
    CHANGE_SIGNUP_NAME: "CHANGE_SIGNUP_NAME",
    CHANGE_SIGNUP_EMAIL: "CHANGE_SIGNUP_EMAIL",
    CHANGE_SIGNUP_PASSWORD: "CHANGE_SIGNUP_PASSWORD",
    SIGNUP_WITH_EMAIL_AND_PASSWORD: "SIGNUP_WITH_EMAIL_AND_PASSWORD",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",

    CHANGE_LOGIN_EMAIL: "CHANGE_LOGIN_EMAIL",
    CHANGE_LOGIN_PASSWORD: "CHANGE_LOGIN_PASSWORD",
    SIGN_IN: "SIGN_IN",
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_FAIL: "SIGN_IN_FAIL",
    TOGGLE_REMEMBER_ME_SWITCH: "TOGGLE_REMEMBER_ME_SWITCH",
};
