export const ActionType = {
    CHANGE_SIGNUP_NAME: "CHANGE_SIGNUP_NAME",
    CHANGE_SIGNUP_EMAIL: "CHANGE_SIGNUP_EMAIL",
    CHANGE_SIGNUP_PASSWORD: "CHANGE_SIGNUP_PASSWORD",
    SIGNUP_WITH_EMAIL_AND_PASSWORD: "SIGNUP_WITH_EMAIL_AND_PASSWORD",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",

    CHANGE_LOGIN_EMAIL: "CHANGE_LOGIN_EMAIL",
    CHANGE_LOGIN_PASSWORD: "CHANGE_LOGIN_PASSWORD",
    SIGN_IN: "SIGN_IN",
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_FAIL: "SIGN_IN_FAIL",
    TOGGLE_REMEMBER_ME_SWITCH: "TOGGLE_REMEMBER_ME_SWITCH",

    CHANGE_AUTHOR: "CHANGE_AUTHOR",
    CHANGE_TITLE: "CHANGE_TITLE",
    CHANGE_COVER: "CHANGE_COVER",
    CHANGE_CATEGORY: "CHANGE_CATEGORY",
    CHANGE_RATE: "CHANGE_RATE",
    CHANGE_STATUS: "CHANGE_STATUS",

    POST_NEW_BOOK: "POST_NEW_BOOK",
    POST_NEW_BOOK_SUCCESS: "POST_NEW_BOOK_SUCCESS",
    POST_NEW_BOOK_FAIL: "POST_NEW_BOOK_FAIL",

    FETCH_BOOKS: "FETCH_BOOKS",
    FETCH_BOOKS_SUCCESS: "FETCH_BOOKS_SUCCESS",
    FETCH_BOOKS_FAIL: "FETCH_BOOKS_FAIL",

    TOGGLE_SIDE_MENU: "TOGGLE_SIDE_MENU",

    DELETE_BOOK: "DELETE_BOOK",
    DELETE_BOOK_SUCCESS: "DELETE_BOOK_SUCCESS",
    DELETE_BOOK_FAIL: "DELETE_BOOK_FAIL",

    SEARCH_BOOK: "SEARCH_BOOK",
    RETURN_TO_BOOKS: "RETURN_TO_BOOKS",
};
